### ISSUE TITLE
Tutorial button how to play the game

### ISSUE THREAD

**Issue by zhangji52** [cs361w2019-osu/sprint1-group-7#18]

**Comment by zhangji52** [comment]
As a user, I want to be able to see some instructions before I start playing the game so that I will know the rules and potentially destroy the enemy and win the game. (gaming experience)
Acceptance tests:
By clicking the tutorial button on the web page, there should be a new page of instructions generated instead of killing the game on the same page; the user can also end the game by clicking the "EXIT" button.
Test/Definition of done: Visual rather than coded test. A user should be able to see the instruction page pop up after clicking the tutorial button, exit the game after clicking the "exit" button.

**Comment by TheREK3R** [comment]
tutorial button works, but does not generate instructions, exit button should be removed, reload button is not properly implemented
