### ISSUE TITLE
Having troubles with adding new ship

### ISSUE THREAD

**Issue by zhangji52** [cs361w2019-osu/sprint1-group-7#53]
Hi, guys! I am trying to implement the new ship submarine, but I am still having troubles putting in the 4th ship to the screen, here's the code I got, I made my changes to green color so that you can see it. Do I have to change other stuff besides the "if placedShip == 4", I am kind of confused.
[question.pdf](https://github.com/cs361w2019-osu/sprint1-group-7/files/2945087/question.pdf)

**Comment by TheREK3R** [comment]
oh sorry i already did that
