### ISSUE TITLE
Feature User choices

### ISSUE THREAD

**Issue by zhangji52** [cs361w2019-osu/sprint1-group-7#8]
As a user, I want to be able to choose a battleship that I like on the board to attack while having 3 moves in total so that I can use strategies while attacking the other player's battleships and win the game.

Acceptance tests:
Click new battleship will give the user the model of the certain ship
Click used battleship will result in an error message "Invalid move." and return nothing
After 3 tries of users, users cannot choose anymore battleship

The webpage of the board game should be refreshed/recorded every time after a user makes a move, users will know the place where they put a battleship; battleship out of the board will result in invalid moves and prompt the user same message to let him know; after hitting an enemy, the certain square will change its color

**Comment by guyera** [comment]
This is already implemented. Check out feature-attack and feature-opponent-attack.
